Initial automation test cases

diff --git a/.github/workflows/postman_collection_runner.yml b/.github/workflows/postman_collection_runner.yml
--- a/.github/workflows/postman_collection_runner.yml
+++ b/.github/workflows/postman_collection_runner.yml
@@ -34,8 +34,10 @@ jobs:
             --iteration-data ${{ github.workspace }}/test/data/QA_Test_Cases.csv \
             -r htmlextra \
             --reporter-htmlextra-export ${{ github.workspace }}/QA_Test_Cases_Report.html
-          echo "exit_code=$?" >> $GITHUB_OUTPUT
-        continue-on-error: true
+          exit_code=$?
+          # Use GITHUB_ENV for cross-step variable
+          echo "exit_code=$exit_code" >> $GITHUB_ENV
+        continue-on-error: true # This lets us still continue after test failure
 
       - name: Sanitize HTML report (replace GitHub secrets with ****)
         run: |
@@ -50,5 +52,7 @@ jobs:
           path: ${{ github.workspace }}/QA_Test_Cases_Report.html
 
       - name: Validate Postman Content Structure Automation Test Outcome
-        if: steps.postman-content-structure-automation-test.outputs.exit_code != '0'
-        run: exit 1
+        if: env.exit_code != '0'
+        run: |
+          echo "Postman tests failed with exit code ${{ env.exit_code }}"
+          exit 1  # Force failure if the exit code is not 0
